import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR_NAME = ".nx-dash";
const GITIGNORE_BODY = "# Auto-generated by nx-dash. Do not commit.\n*\n";

export function nxDashDir(workspaceRoot: string): string {
  return join(workspaceRoot, DIR_NAME);
}

export function ensureSelfIgnoredDir(workspaceRoot: string): string {
  const dir = nxDashDir(workspaceRoot);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const giPath = join(dir, ".gitignore");
  if (!existsSync(giPath)) {
    writeFileSync(giPath, GITIGNORE_BODY, "utf8");
  }
  return dir;
}
